services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NUXT_OPENAI_API_KEY: ${NUXT_OPENAI_API_KEY}
      NUXT_OAUTH_GOOGLE_CLIENT_ID: ${NUXT_OAUTH_GOOGLE_CLIENT_ID}
      NUXT_OAUTH_GOOGLE_CLIENT_SECRET: ${NUXT_OAUTH_GOOGLE_CLIENT_SECRET}
      NUXT_SESSION_PASSWORD: ${NUXT_SESSION_PASSWORD}
      NUXT_ALLOWED_EMAILS: ${NUXT_ALLOWED_EMAILS}
    restart: unless-stopped
