services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NUXT_OPENAI_API_KEY: ${NUXT_OPENAI_API_KEY}
      NUXT_OAUTH_GOOGLE_CLIENT_ID: ${NUXT_OAUTH_GOOGLE_CLIENT_ID}
      NUXT_OAUTH_GOOGLE_CLIENT_SECRET: ${NUXT_OAUTH_GOOGLE_CLIENT_SECRET}
      NUXT_OAUTH_GOOGLE_REDIRECT_URL: ${NUXT_OAUTH_GOOGLE_REDIRECT_URL}
      NUXT_AUTH_ALLOWED_EMAILS: ${NUXT_AUTH_ALLOWED_EMAILS}
      NUXT_AUTH_JWT_SECRET: ${NUXT_AUTH_JWT_SECRET}
    restart: unless-stopped
